begin;

create table if not exists public.centres (
  id smallint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  short_name text not null,
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint centres_code_format check (code ~ '^[A-Z0-9_]+$'),
  constraint centres_name_length check (char_length(name) between 2 and 100),
  constraint centres_short_name_length check (char_length(short_name) between 2 and 50)
);

alter table public.centres enable row level security;

insert into public.centres (code, name, short_name, sort_order, is_active)
values
  ('EAST_STATION', 'Ambernath East - Near Station', 'East - Near Station', 1, true),
  ('WEST_NISARG', 'Ambernath West - Nisarg Greens', 'West - Nisarg Greens', 2, true),
  ('FATHER_AGNEL', 'Father Agnel Side', 'Father Agnel Side', 3, true)
on conflict (code) do update
set name = excluded.name,
    short_name = excluded.short_name,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active;

alter table public.profiles
  add column if not exists centre_id smallint;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_centre_id_fkey'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_centre_id_fkey
      foreign key (centre_id) references public.centres(id)
      on update restrict on delete restrict;
  end if;
end
$$;

create index if not exists profiles_student_centre_idx
  on public.profiles (centre_id)
  where role = 'student';

create table if not exists public.student_centre_history (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  old_centre_id smallint references public.centres(id) on update restrict on delete restrict,
  new_centre_id smallint not null references public.centres(id) on update restrict on delete restrict,
  changed_by uuid not null references public.profiles(id) on update restrict on delete restrict,
  changed_at timestamptz not null default now()
);

alter table public.student_centre_history enable row level security;

create index if not exists student_centre_history_student_changed_idx
  on public.student_centre_history (student_id, changed_at desc);

create index if not exists student_centre_history_changed_by_idx
  on public.student_centre_history (changed_by);

create index if not exists student_centre_history_old_centre_idx
  on public.student_centre_history (old_centre_id);

create index if not exists student_centre_history_new_centre_idx
  on public.student_centre_history (new_centre_id);

create or replace function public.admin_list_centres()
returns table (
  id smallint,
  code text,
  name text,
  short_name text,
  sort_order smallint,
  active_student_count bigint
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  return query
  select c.id,
         c.code,
         c.name,
         c.short_name,
         c.sort_order,
         count(p.id) filter (where p.role = 'student' and p.is_active is distinct from false)
  from public.centres c
  left join public.profiles p on p.centre_id = c.id
  where c.is_active = true
  group by c.id, c.code, c.name, c.short_name, c.sort_order
  order by c.sort_order, c.name;
end;
$$;

drop function if exists public.admin_list_student_levels();

create function public.admin_list_student_levels()
returns table (
  id uuid,
  full_name text,
  email text,
  current_level integer,
  batch_name text,
  centre_id smallint,
  centre_name text,
  centre_short_name text,
  is_active boolean,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  return query
  select p.id,
         p.full_name,
         u.email::text,
         p.current_level,
         p.batch_name,
         p.centre_id,
         c.name,
         c.short_name,
         p.is_active,
         p.created_at
  from public.profiles p
  join auth.users u on u.id = p.id
  left join public.centres c on c.id = p.centre_id
  where p.role = 'student'
  order by coalesce(p.is_active, false) desc,
           c.sort_order nulls first,
           lower(coalesce(p.batch_name, '')),
           lower(coalesce(p.full_name, u.email, ''));
end;
$$;

create or replace function public.admin_update_student_centre(
  p_student_id uuid,
  p_centre_id smallint
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old_centre_id smallint;
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  if not exists (
    select 1 from public.centres c
    where c.id = p_centre_id and c.is_active = true
  ) then
    raise exception 'Active centre not found';
  end if;

  select p.centre_id
  into v_old_centre_id
  from public.profiles p
  where p.id = p_student_id and p.role = 'student'
  for update;

  if not found then
    raise exception 'Student not found';
  end if;

  if v_old_centre_id is distinct from p_centre_id then
    update public.profiles
    set centre_id = p_centre_id
    where id = p_student_id and role = 'student';

    insert into public.student_centre_history (
      student_id, old_centre_id, new_centre_id, changed_by
    ) values (
      p_student_id, v_old_centre_id, p_centre_id, auth.uid()
    );
  end if;
end;
$$;

create or replace function public.admin_bulk_update_student_centres(
  p_student_ids uuid[],
  p_centre_id smallint
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
  v_old_centre_id smallint;
  v_count integer := 0;
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  if p_student_ids is null or array_length(p_student_ids, 1) is null then
    return 0;
  end if;

  if not exists (
    select 1 from public.centres c
    where c.id = p_centre_id and c.is_active = true
  ) then
    raise exception 'Active centre not found';
  end if;

  foreach v_id in array p_student_ids loop
    select p.centre_id
    into v_old_centre_id
    from public.profiles p
    where p.id = v_id and p.role = 'student'
    for update;

    if found and v_old_centre_id is distinct from p_centre_id then
      update public.profiles
      set centre_id = p_centre_id
      where id = v_id and role = 'student';

      insert into public.student_centre_history (
        student_id, old_centre_id, new_centre_id, changed_by
      ) values (
        v_id, v_old_centre_id, p_centre_id, auth.uid()
      );

      v_count := v_count + 1;
    end if;
  end loop;

  return v_count;
end;
$$;

revoke all on table public.centres from anon, authenticated;
revoke all on table public.student_centre_history from anon, authenticated;

revoke execute on function public.admin_list_centres() from public, anon;
revoke execute on function public.admin_list_student_levels() from public, anon;
revoke execute on function public.admin_update_student_centre(uuid, smallint) from public, anon;
revoke execute on function public.admin_bulk_update_student_centres(uuid[], smallint) from public, anon;
revoke execute on function public.admin_bulk_update_student_batches(uuid[], text) from public, anon;
revoke execute on function public.admin_bulk_update_student_levels(uuid[], integer) from public, anon;
revoke execute on function public.admin_recent_level_changes(integer) from public, anon;
revoke execute on function public.admin_update_student_batch(uuid, text) from public, anon;
revoke execute on function public.admin_update_student_level(uuid, integer) from public, anon;
revoke execute on function public.current_user_is_admin() from public, anon;

grant execute on function public.admin_list_centres() to authenticated;
grant execute on function public.admin_list_student_levels() to authenticated;
grant execute on function public.admin_update_student_centre(uuid, smallint) to authenticated;
grant execute on function public.admin_bulk_update_student_centres(uuid[], smallint) to authenticated;
grant execute on function public.admin_bulk_update_student_batches(uuid[], text) to authenticated;
grant execute on function public.admin_bulk_update_student_levels(uuid[], integer) to authenticated;
grant execute on function public.admin_recent_level_changes(integer) to authenticated;
grant execute on function public.admin_update_student_batch(uuid, text) to authenticated;
grant execute on function public.admin_update_student_level(uuid, integer) to authenticated;

commit;
