begin;

alter table public.profiles
  add column if not exists student_status text not null default 'active',
  add column if not exists status_changed_at timestamptz not null default now(),
  add column if not exists status_reason text,
  add column if not exists status_note text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_student_status_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_student_status_check
      check (student_status in ('active', 'on_hold', 'dropped_out', 'passed_out', 'not_enrolled'));
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_status_reason_length'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_status_reason_length
      check (status_reason is null or char_length(status_reason) <= 150);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_status_note_length'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_status_note_length
      check (status_note is null or char_length(status_note) <= 500);
  end if;
end
$$;

create index if not exists profiles_student_status_idx
  on public.profiles (student_status)
  where role = 'student';

create index if not exists profiles_student_status_centre_idx
  on public.profiles (student_status, centre_id)
  where role = 'student';

create index if not exists reports_user_practice_time_idx
  on public.reports (user_id, indian_time desc);

create table if not exists public.student_status_history (
  id bigint generated by default as identity primary key,
  student_id uuid not null references public.profiles(id) on delete cascade,
  old_status text,
  new_status text not null,
  reason text not null,
  note text,
  changed_by uuid not null references public.profiles(id) on update restrict on delete restrict,
  changed_at timestamptz not null default now(),
  constraint student_status_history_old_status_check
    check (old_status is null or old_status in ('active', 'on_hold', 'dropped_out', 'passed_out', 'not_enrolled')),
  constraint student_status_history_new_status_check
    check (new_status in ('active', 'on_hold', 'dropped_out', 'passed_out', 'not_enrolled')),
  constraint student_status_history_reason_length
    check (char_length(btrim(reason)) between 1 and 150),
  constraint student_status_history_note_length
    check (note is null or char_length(note) <= 500)
);

alter table public.student_status_history enable row level security;

create index if not exists student_status_history_student_changed_idx
  on public.student_status_history (student_id, changed_at desc);

create index if not exists student_status_history_changed_by_idx
  on public.student_status_history (changed_by);

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role = 'admin'
      and coalesce(p.is_active, true) = true
  );
$$;

create or replace function public.current_user_is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.is_active is true
      and p.role in ('admin', 'teacher')
  );
$$;

create or replace function public.admin_list_centres()
returns table (
  id smallint,
  code text,
  name text,
  short_name text,
  sort_order smallint,
  active_student_count bigint
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  return query
  select c.id,
         c.code,
         c.name,
         c.short_name,
         c.sort_order,
         count(p.id) filter (
           where p.role = 'student'
             and p.student_status = 'active'
             and p.is_active is true
         )
  from public.centres c
  left join public.profiles p on p.centre_id = c.id
  where c.is_active = true
  group by c.id, c.code, c.name, c.short_name, c.sort_order
  order by c.sort_order, c.name;
end;
$$;

drop function if exists public.admin_list_student_levels();

create function public.admin_list_student_levels()
returns table (
  id uuid,
  full_name text,
  email text,
  current_level integer,
  batch_name text,
  centre_id smallint,
  centre_name text,
  centre_short_name text,
  is_active boolean,
  student_status text,
  status_changed_at timestamptz,
  status_reason text,
  status_note text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  return query
  select p.id,
         p.full_name,
         u.email::text,
         p.current_level,
         p.batch_name,
         p.centre_id,
         c.name,
         c.short_name,
         p.is_active,
         p.student_status,
         p.status_changed_at,
         p.status_reason,
         p.status_note,
         p.created_at
  from public.profiles p
  join auth.users u on u.id = p.id
  left join public.centres c on c.id = p.centre_id
  where p.role = 'student'
  order by case p.student_status
             when 'active' then 1
             when 'on_hold' then 2
             when 'not_enrolled' then 3
             when 'passed_out' then 4
             when 'dropped_out' then 5
             else 6
           end,
           coalesce(p.is_active, false) desc,
           c.sort_order nulls first,
           lower(coalesce(p.batch_name, '')),
           lower(coalesce(p.full_name, u.email, ''));
end;
$$;

create or replace function public.admin_update_student_status(
  p_student_id uuid,
  p_new_status text,
  p_reason text,
  p_note text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old_status text;
  v_reason text := nullif(btrim(p_reason), '');
  v_note text := nullif(btrim(p_note), '');
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  if p_new_status is null or p_new_status not in ('active', 'on_hold', 'dropped_out', 'passed_out', 'not_enrolled') then
    raise exception 'Invalid student status';
  end if;

  if v_reason is null or char_length(v_reason) > 150 then
    raise exception 'A status reason of 1 to 150 characters is required';
  end if;

  if v_note is not null and char_length(v_note) > 500 then
    raise exception 'Status note must be 500 characters or less';
  end if;

  select p.student_status
  into v_old_status
  from public.profiles p
  where p.id = p_student_id and p.role = 'student'
  for update;

  if not found then
    raise exception 'Student not found';
  end if;

  if v_old_status is distinct from p_new_status then
    update public.profiles
    set student_status = p_new_status,
        status_changed_at = now(),
        status_reason = v_reason,
        status_note = v_note
    where id = p_student_id and role = 'student';

    insert into public.student_status_history (
      student_id, old_status, new_status, reason, note, changed_by
    ) values (
      p_student_id, v_old_status, p_new_status, v_reason, v_note, auth.uid()
    );
  end if;
end;
$$;

create or replace function public.admin_bulk_update_student_statuses(
  p_student_ids uuid[],
  p_new_status text,
  p_reason text,
  p_note text default null
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id uuid;
  v_old_status text;
  v_reason text := nullif(btrim(p_reason), '');
  v_note text := nullif(btrim(p_note), '');
  v_count integer := 0;
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  if p_student_ids is null or array_length(p_student_ids, 1) is null then
    return 0;
  end if;

  if p_new_status is null or p_new_status not in ('active', 'on_hold', 'dropped_out', 'passed_out', 'not_enrolled') then
    raise exception 'Invalid student status';
  end if;

  if v_reason is null or char_length(v_reason) > 150 then
    raise exception 'A status reason of 1 to 150 characters is required';
  end if;

  if v_note is not null and char_length(v_note) > 500 then
    raise exception 'Status note must be 500 characters or less';
  end if;

  foreach v_id in array p_student_ids loop
    select p.student_status
    into v_old_status
    from public.profiles p
    where p.id = v_id and p.role = 'student'
    for update;

    if found and v_old_status is distinct from p_new_status then
      update public.profiles
      set student_status = p_new_status,
          status_changed_at = now(),
          status_reason = v_reason,
          status_note = v_note
      where id = v_id and role = 'student';

      insert into public.student_status_history (
        student_id, old_status, new_status, reason, note, changed_by
      ) values (
        v_id, v_old_status, p_new_status, v_reason, v_note, auth.uid()
      );

      v_count := v_count + 1;
    end if;
  end loop;

  return v_count;
end;
$$;

create or replace function public.admin_recent_status_changes(p_limit integer default 50)
returns table (
  student_id uuid,
  student_name text,
  old_status text,
  new_status text,
  reason text,
  note text,
  changed_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.current_user_is_admin() then
    raise exception 'Admin access required';
  end if;

  return query
  select h.student_id,
         coalesce(nullif(btrim(p.full_name), ''), u.email::text, 'Student'),
         h.old_status,
         h.new_status,
         h.reason,
         h.note,
         h.changed_at
  from public.student_status_history h
  join public.profiles p on p.id = h.student_id
  left join auth.users u on u.id = h.student_id
  order by h.changed_at desc
  limit greatest(1, least(coalesce(p_limit, 50), 200));
end;
$$;

create or replace function public.staff_active_student_practice_overview()
returns table (
  user_id uuid,
  student_name text,
  level integer,
  batch_name text,
  centre_id smallint,
  centre_name text,
  last_practice_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.current_user_is_staff() then
    raise exception 'Staff access required';
  end if;

  return query
  select p.id,
         coalesce(nullif(btrim(p.full_name), ''), 'Student'),
         p.current_level,
         p.batch_name,
         p.centre_id,
         c.short_name,
         max(r.indian_time) as last_practice_at
  from public.profiles p
  left join public.centres c on c.id = p.centre_id
  left join public.reports r on r.user_id = p.id
  where p.role = 'student'
    and p.is_active is true
    and p.student_status = 'active'
  group by p.id, p.full_name, p.current_level, p.batch_name, p.centre_id, c.short_name
  order by lower(coalesce(p.batch_name, '')), p.current_level, lower(coalesce(p.full_name, 'Student'));
end;
$$;

create or replace function public.staff_list_active_formula_students()
returns table (id uuid, full_name text, current_level integer)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.current_user_is_staff() then
    raise exception 'Staff access required';
  end if;

  return query
  select p.id,
         coalesce(nullif(btrim(p.full_name), ''), 'Student'),
         p.current_level
  from public.profiles p
  where p.role = 'student'
    and p.is_active is true
    and p.student_status = 'active'
    and p.current_level in (1, 2)
  order by p.current_level, lower(coalesce(p.full_name, 'Student'));
end;
$$;

create or replace function public.staff_official_daily_practice_status(
  p_date date default ((now() at time zone 'Asia/Kolkata')::date)
)
returns table (
  user_id uuid,
  student_name text,
  level integer,
  batch_name text,
  practice_id uuid,
  practice_status text,
  completed_sections text[],
  responses jsonb,
  section_seconds jsonb,
  completed_at timestamptz,
  retry_summary jsonb
)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.current_user_is_staff() then
    raise exception 'Staff access required';
  end if;

  return query
  select p.id,
         coalesce(p.full_name, 'Student'),
         p.current_level,
         p.batch_name,
         odp.id,
         coalesce(odp.status, 'not_started'),
         coalesce(odp.completed_sections, '{}'::text[]),
         coalesce(odp.responses, '{}'::jsonb),
         coalesce(odp.section_seconds, '{}'::jsonb),
         odp.completed_at,
         coalesce(r.retry_summary, '[]'::jsonb)
  from public.profiles p
  left join public.official_daily_practice odp
    on odp.user_id = p.id
   and odp.practice_date = p_date
  left join lateral (
    select jsonb_agg(
      jsonb_build_object(
        'section', rr.section,
        'retry_type', rr.retry_type,
        'completed', rr.completed,
        'correct_count', rr.correct_count,
        'wrong_count', rr.wrong_count,
        'skipped_count', rr.skipped_count,
        'duration_seconds', rr.duration_seconds,
        'created_at', rr.created_at,
        'completed_at', rr.completed_at
      ) order by rr.created_at
    ) as retry_summary
    from public.official_daily_practice_retries rr
    where rr.official_daily_practice_id = odp.id
  ) r on true
  where p.role = 'student'
    and p.is_active is true
    and p.student_status = 'active'
    and p.current_level between 2 and 8
  order by lower(coalesce(p.batch_name, '')), p.current_level, lower(coalesce(p.full_name, 'Student'));
end;
$$;

with target as (
  select p.id, p.student_status as old_status
  from public.profiles p
  join auth.users u on u.id = p.id
  where p.role = 'student'
    and lower(u.email) = lower('kaira.kamble@gmail.com')
    and lower(coalesce(p.full_name, '')) = lower('Kaira Kamble')
), updated as (
  update public.profiles p
  set student_status = 'not_enrolled',
      status_changed_at = now(),
      status_reason = 'Owner family account',
      status_note = 'Login access retained; excluded from enrolled student counts.',
      centre_id = null
  from target t
  where p.id = t.id
    and p.student_status is distinct from 'not_enrolled'
  returning p.id, t.old_status
), admin_user as (
  select p.id
  from public.profiles p
  join auth.users u on u.id = p.id
  where p.role = 'admin'
    and p.is_active is true
    and lower(u.email) = lower('admin.ambernath@gmail.com')
  limit 1
)
insert into public.student_status_history (
  student_id, old_status, new_status, reason, note, changed_by
)
select updated.id,
       updated.old_status,
       'not_enrolled',
       'Owner family account',
       'Login access retained; excluded from enrolled student counts.',
       admin_user.id
from updated
cross join admin_user;

revoke all on table public.student_status_history from anon, authenticated;

revoke execute on function public.current_user_is_admin() from public, anon;
revoke execute on function public.current_user_is_staff() from public, anon;
revoke execute on function public.current_user_is_admin() from authenticated;
revoke execute on function public.current_user_is_staff() from authenticated;
revoke execute on function public.admin_list_centres() from public, anon;
revoke execute on function public.admin_list_student_levels() from public, anon;
revoke execute on function public.admin_update_student_status(uuid, text, text, text) from public, anon;
revoke execute on function public.admin_bulk_update_student_statuses(uuid[], text, text, text) from public, anon;
revoke execute on function public.admin_recent_status_changes(integer) from public, anon;
revoke execute on function public.staff_active_student_practice_overview() from public, anon;
revoke execute on function public.staff_list_active_formula_students() from public, anon;
revoke execute on function public.staff_official_daily_practice_status(date) from public, anon;

grant execute on function public.admin_list_centres() to authenticated;
grant execute on function public.admin_list_student_levels() to authenticated;
grant execute on function public.admin_update_student_status(uuid, text, text, text) to authenticated;
grant execute on function public.admin_bulk_update_student_statuses(uuid[], text, text, text) to authenticated;
grant execute on function public.admin_recent_status_changes(integer) to authenticated;
grant execute on function public.staff_active_student_practice_overview() to authenticated;
grant execute on function public.staff_list_active_formula_students() to authenticated;
grant execute on function public.staff_official_daily_practice_status(date) to authenticated;

commit;
